/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 死活確認（F-39）
         * @description 認証を要さない。DB・Redis 等に問い合わせない（機能一覧 14.1）。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新規登録（F-01 / F-03 / F-37）
         * @description 認証を要さない。登録と同時にログイン状態にはしない（トークンは返さない）。 リカバリーコードはこの応答でだけ返し、以後は再表示できない（機能一覧 1.1）。 発信元単位のレート制限は1時間に10回（機能一覧 1.1）。201・403・409 の要求も1回として数え、 入力の検証で落ちた要求（400）は数えない。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン（F-02）
         * @description 認証を要さない。成功するとアクセストークン（JWT・15分）を本体で返し、リフレッシュトークン（14日）を Cookie（refresh_token。HttpOnly; Secure; SameSite=Strict; Path=/api/auth）で渡す（機能一覧 1.2）。 発信元単位のレート制限は15分に20回。加えてユーザーID（大文字小文字を区別しない。存在しない ID も同じ）ごとに、 連続して失敗した回数 n に対し 2^(n-1) 秒（上限 900 秒）の間は照合せずに 429 を返す。成功で数え直す。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * アクセストークンの更新（F-02）
         * @description Cookie（refresh_token）のリフレッシュトークンを新しいものに入れ替え、新しいアクセストークンを返す（機能一覧 1.2）。 入れ替え済みのトークンが出されたら、そのログインの系列のトークンをすべて失効させる（RFC 9700 4.14.2）。 本体は送らない。X-Requested-By が無い要求は 400、Sec-Fetch-Site / Origin / Referer が同じ origin を示さない要求は 403 （要件定義書 4.3 の CSRF の対処）。
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウト（F-02）
         * @description Cookie（refresh_token）のリフレッシュトークンの系列をすべて失効させ、Cookie を消す（機能一覧 1.2）。 トークンが無い・知らない場合も 204 を返す。本体は送らない。CSRF の対処は /auth/refresh と同じ。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * リカバリーコードによるパスワードの再設定（F-37）
         * @description 認証を要さない。ユーザーID とリカバリーコードでパスワードを再設定し、使ったコードを無効化して新しいコードを発行する （新しいコードはこの応答でだけ返す）。その利用者のリフレッシュトークンをすべて失効させる（機能一覧 1.1）。 発信元単位のレート制限は1時間に10回。加えてユーザーID（大文字小文字を区別しない。存在しない ID も同じ）ごとに、 連続して失敗した回数 n に対し 2^(n-1) 秒（上限 900 秒）の間は照合せずに 429 を返す（ログインとは別に数える）。
         */
        post: operations["recover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description エラーの種類。api が返す値はこの列挙だけであり、api と web は生成した型で同じ列挙を使う （綴りを誤ると型検査で落ちる）
             * @enum {string}
             */
            code: "validation_failed" | "invalid_body" | "not_found" | "method_not_allowed" | "payload_too_large" | "unsupported_media_type" | "too_many_requests" | "user_id_taken" | "registration_disabled" | "invalid_credentials" | "invalid_token" | "csrf_rejected" | "request_rejected" | "internal_error";
            message: string;
            /** @description 入力の検証で落ちた箇所。送られた値は含めない */
            errors?: {
                path: string;
                message: string;
            }[];
        };
        RegisterRequest: {
            /** @description 英数字とアンダースコアのみ、3〜30文字（機能一覧 1.1） */
            userId: string;
            /** @description 8〜128文字（機能一覧 1.1。上限は決定・2026-09-11・依頼側）。文字数はコードポイントで数える */
            password: string;
            /** @description 1〜50文字。空白だけは不可（機能一覧 1.1。決定・2026-09-11・依頼側。列の型にも入れてある） */
            displayName: string;
        };
        RecoveryRequest: {
            /** @description 英数字とアンダースコアのみ、3〜30文字（RegisterRequest と同じ） */
            userId: string;
            /** @description 登録で受け取ったコード。英小文字・ハイフンの有無を問わない（照合の前に正規形へ寄せる。O は 0、I・L は 1 と読む） */
            recoveryCode: string;
            /** @description 8〜128文字（RegisterRequest の password と同じ） */
            newPassword: string;
        };
        RecoveryResponse: {
            /** @description 新しいリカバリーコード。Crockford の Base32 で16文字（80ビット）を4文字ずつハイフンで区切る */
            recoveryCode: string;
        };
        RegisterResponse: {
            user: components["schemas"]["UserSummary"];
            /** @description Crockford の Base32 で16文字（80ビット）を4文字ずつハイフンで区切る */
            recoveryCode: string;
        };
        LoginRequest: {
            /** @description 英数字とアンダースコアのみ、3〜30文字（RegisterRequest と同じ） */
            userId: string;
            /** @description 1〜128文字。下限を登録（8文字）に揃えないのは、下限を変えたときに既存の利用者がログインできなくならないようにするため */
            password: string;
        };
        RefreshResponse: {
            /** @description JWT（HS256）。Authorization ヘッダーに Bearer で付ける */
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /** @description アクセストークンの有効期間（秒） */
            expiresIn: number;
        };
        LoginResponse: {
            /** @description JWT（HS256）。Authorization ヘッダーに Bearer で付ける */
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /** @description アクセストークンの有効期間（秒） */
            expiresIn: number;
            user: components["schemas"]["UserSummary"];
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            userId: string;
            displayName: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
    };
    responses: {
        /** @description Sec-Fetch-Site・Origin・Referer のどれも、api と同じ origin からの要求であることを示さない（csrf_rejected） */
        CsrfRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 入力が仕様に合わない（validation_failed）か、本体を JSON として読めない（invalid_body）。 どちらも送られた値を応答に載せない */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 仕様に無いメソッド（method_not_allowed） */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 本体が大きすぎる（payload_too_large。上限は Nest の JSON の読み取りの既定の 100kb） */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 仕様に無いメディア型の本体（unsupported_media_type） */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description レート制限を超えた（too_many_requests。上限はパスの説明に書く） */
        TooManyRequests: {
            headers: {
                /** @description 再び受け付けるまでの秒数 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 想定外の失敗（internal_error）。例外のメッセージは載せない */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Cookie を使う要求であることを示す独自のヘッダー。ブラウザは独自のヘッダーを付けた別の origin からの要求に プリフライトを求めるため、フォームや画像の読み込みからは送れない（要件定義書 4.3） */
        RequestedBy: "workspace-chat";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 稼働している */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 登録した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 新規登録を停止している（registration_disabled。要件定義書 5.1） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description ユーザーID が既に使われている（user_id_taken。大文字小文字だけの違いも同じ ID と見なす）。 代償: どのユーザーID が登録済みかがこの応答で分かり、列挙に使える（ログインは区別しない。機能一覧 1.2）。 利用者が別の ID を選び直せることを優先した。列挙は発信元単位のレート制限（429）で抑える */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description ログインした */
            200: {
                headers: {
                    /** @description リフレッシュトークン（refresh_token） */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description ユーザーID かパスワードが違う、または退会済み（invalid_credentials）。どれに当たったかは区別しない（機能一覧 1.2） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header: {
                /** @description Cookie を使う要求であることを示す独自のヘッダー。ブラウザは独自のヘッダーを付けた別の origin からの要求に プリフライトを求めるため、フォームや画像の読み込みからは送れない（要件定義書 4.3） */
                "X-Requested-By": components["parameters"]["RequestedBy"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 入れ替えた */
            200: {
                headers: {
                    /** @description 新しいリフレッシュトークン（refresh_token） */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description リフレッシュトークンが無い・知らない・失効済み・期限切れ、または利用者が退会済み（invalid_token）。 どれに当たったかは区別しない。Cookie を消す */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["CsrfRejected"];
            405: components["responses"]["MethodNotAllowed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Cookie を使う要求であることを示す独自のヘッダー。ブラウザは独自のヘッダーを付けた別の origin からの要求に プリフライトを求めるため、フォームや画像の読み込みからは送れない（要件定義書 4.3） */
                "X-Requested-By": components["parameters"]["RequestedBy"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログアウトした（Cookie を消す） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["CsrfRejected"];
            405: components["responses"]["MethodNotAllowed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    recover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryRequest"];
            };
        };
        responses: {
            /** @description 再設定した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description ユーザーID かリカバリーコードが違う、コードが使用済み、または退会済み（invalid_credentials）。どれに当たったかは区別しない */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
